name: Bug Report
description: File a bug report
title: "[Bug] "
labels:
  - bug
assignees:
  - isxander
body:
  - type: markdown
    attributes:
      value: |
        **Please fill out the following information to help in fixing the bug.
  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: A clear and concise description of what you're experiencing.
      placeholder: I do this and this happens.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what you expected to happen.
      placeholder: I do this and this happens.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: |
        Paste screenshots here.
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs to help explain your problem.
      render: shell
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Mod Version
      description: The version of the mod you used to produce this bug. *Make sure to include the Minecraft version!*
      placeholder: 1.3.1+1.20
    validations:
      required: true
  - type: input
    id: controller
    attributes:
      label: Controller
      description: The controller you used. *Provide the link to the product page if possible.*
      placeholder: Xbox Series Controller
  - type: checkboxes
    id: bluetooth
    attributes:
      label: Bluetooth
      description: Did you use Bluetooth to connect your controller? *This does **not** include the Xbox Wireless Adapter dongle.*
      options:
        - label: "Yes"
          required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: The operating system you're using.
      multiple: false
      options:
        - Windows
        - macOS
        - Linux/SteamOS
    validations:
      required: true
  - type: checkboxes
    id: arm
    attributes:
      label: ARM
      description: Are you using an ARM-based device? This includes Apple Silicon.
      options:
        - label: "Yes"
          required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
      placeholder: |
        Add any other context about the problem here.
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Just to make sure...
      description: "By submitting this issue, you confirm you have done the following things:"
      options:
        - label: I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
          required: true
        - label: I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).
          required: true

